### ISSUE TITLE
Error adding image/ic_lens

### ISSUE THREAD

**Issue by kimkimkeren** [konifar/android-material-design-icon-generator-plugin#33]
The stacktrace :

> input == null!
> java.lang.IllegalArgumentException: input == null!
>         at javax.imageio.ImageIO.read(ImageIO.java:1348)
>         at com.konifar.material_icon_generator.MaterialDesignIconGenerateDialog.copyFile(MaterialDesignIconGenerateDialog.java:461)
>     at com.konifar.material_icon_generator.MaterialDesignIconGenerateDialog.createIcon(MaterialDesignIconGenerateDialog.java:450)
>     at com.konifar.material_icon_generator.MaterialDesignIconGenerateDialog.create(MaterialDesignIconGenerateDialog.java:417)
>     at com.konifar.material_icon_generator.MaterialDesignIconGenerateDialog.doOKAction(MaterialDesignIconGenerateDialog.java:411)
>     at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1821)
>     at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1787)
>     at ...

**Comment by shiraji** [comment]
There is no `icons/image/drawable-hdpi/ic_lens_white_18dp.png`

**Comment by kimkimkeren** [comment]
But there is, in Google Material Icons
https://www.google.com/design/icons/#ic_lens

Maybe that icon will be added in Android Studio 1.4
